name: Status Check
on:
  push:
    branches:
      - '**'
      - '!master'

jobs:
  check1:
    runs-on: ubuntu-latest

    steps:
      - name: something test1
        run: |
          sleep 30
          exit 0

  check2:
    runs-on: ubuntu-latest

    steps:
      - name: something test2
        run: exit 0
